[package]

name        = "hkdf"
version     = "0.1.0"
authors     = ["Toralf Wittner <tw@dtex.org>"]
description = "HKDF implementation (RFC 5869)"
homepage    = "https://github.com/twittner/hkdf"
repository  = "git@github.com:twittner/hkdf.git"
license     = "MPL-2.0"

[dependencies]
sodiumoxide = "> 0.0.4"

[dev-dependencies]
rustc-serialize = "> 0.3.0"
